name: Build Custom Ubuntu Runner Image

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      LOCATION: switzerlandnorth
      PACKER_VERSION: "1.14.3"
      IMAGE_NAME: action-runner-ubuntu2404-${{ github.run_number }}
      IMAGE_OS: ubuntu24
      GALLERY_NAME: "sig-gha-images-swn"
      IMAGE_DEFINITION: "github-runner-ubuntu-2404"
      TEMPLATE_PATH: images/ubuntu/templates/
      BUILD_NAME: ubuntu-24_04.azure-arm.image
      IMAGE_VERSION: "1.0.${{ github.run_number }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Verify Packer installation
        run: packer version

      - name: Install Packer Azure Plugin
        run: packer plugins install github.com/hashicorp/azure

      - name: Initialize Packer
        run: |
          packer init ${{ env.TEMPLATE_PATH }}

      - name: Format Packer
        run: |
          packer fmt ${{ env.TEMPLATE_PATH }}

      - name: Validate Packer template
        run: |
          packer validate \
            -only="${{ env.BUILD_NAME }}" \
            -var="use_azure_cli_auth=true" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="managed_image_name=${{ env.IMAGE_NAME }}" \
            -var="managed_image_resource_group_name=${{ secrets.IMAGE_RESOURCE_GROUP }}" \
            -var="image_os=${{ env.IMAGE_OS }}" \
            -var="build_resource_group_name=${{ secrets.BUILD_RG_NAME }}" \
            -var="shared_image_gallery_destination.resource_group=${{ secrets.IMAGE_RESOURCE_GROUP }}" \
            -var="shared_image_gallery_destination.gallery_name=${{ env.GALLERY_NAME }}" \
            -var="shared_image_gallery_destination.image_name=${{ env.IMAGE_DEFINITION }}" \
            -var="shared_image_gallery_destination.image_version=${{ env.IMAGE_VERSION }}" \
            ${{ env.TEMPLATE_PATH }}

      - name: Build Image with Packer
        run: |
          packer build \
            -only="${{ env.BUILD_NAME }}" \
            -var="use_azure_cli_auth=true" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="managed_image_name=${{ env.IMAGE_NAME }}" \
            -var="managed_image_resource_group_name=${{ secrets.IMAGE_RESOURCE_GROUP }}" \
            -var="image_os=${{ env.IMAGE_OS }}" \
            -var="build_resource_group_name=${{ secrets.BUILD_RG_NAME }}" \
            -var="shared_image_gallery_destination.resource_group=${{ secrets.IMAGE_RESOURCE_GROUP }} \
            -var="shared_image_gallery_destination.gallery_name=${{ env.GALLERY_NAME }}" \
            -var="shared_image_gallery_destination.image_name=${{ env.IMAGE_DEFINITION }}" \
            -var="shared_image_gallery_destination.image_version=${{ env.IMAGE_VERSION }}" \
            ${{ env.TEMPLATE_PATH }}
